shop/main/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls')),
    path('api/api/', include('api.urls')), 
    
    
    
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

shop/shop/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from main import views
from django.conf.urls.static import static
from django.contrib.auth import views as auth_view

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)

from main import api_views


urlpatterns = [
    # path('', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('index', views.index, name="index"),
    path('login/', views.CustomLoginView.as_view(), name="login"),
    path('register', views.RegisterView.as_view(), name = 'register'),
    path('book/<int:book_id>',views.book, name='book'),
    path('book/<int:book_id>/page/<int:page_id>',views.page, name='page'),
    path('book/<int:book_id>/page/<int:page_id>/take/<int:item_id>',views.take, name='take'),
    path('page_add',views.AddPageView.as_view(), name = 'add'),
    path('logout_user', views.logout_user, name= 'logout' ),
    path('about', views.about, name="about"),
    path('api/api/dfdasdas/', api_views.BookView.as_view()), 
    
    path('password_reset/', views.password_reset_request, name = 'password_reset' ),
    path('password_reset_done', auth_view.PasswordResetDoneView.as_view(template_name='main/password_reset_done.html'),
         name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', auth_view.PasswordResetConfirmView.as_view(template_name='main/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password_reset_complete/', auth_view.PasswordResetCompleteView.as_view(template_name='main/password_reset_complete.html'),
         name='password_reset_complete'),
    # path('main_game', views.index),
    
    
    
    
    path ('api/users/', views.UserListView.as_view(), name ='get_users'),
    path ('api/token/', TokenObtainPairView.as_view(), name ='token_obtain_pair' ),
    path ('api/token/refresh/', TokenRefreshView.as_view(), name ='token_refresh' ),
    path('api/token/verify', TokenVerifyView.as_view(), name = 'token_varify'),
    
    # path('sign_up/', views.sign_up, name='users-sign-up'),
    # path('profile/', views.profile, name='users-profile'),
    # path('log', auth_view.LoginView.as_view(template_name='login.html'),
    #      name='users-login'),
    # path('logout/', auth_view.LogoutView.as_view(template_name='users/logout.html'),
    #      name='users-logout'),
    # path('password_reset/', auth_view.PasswordResetView.as_view(template_name='users/password_reset.html'),
    #      name='password_reset'),
    # path('password_reset_done/', auth_view.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
    #      name='password_reset_done'),
    # path('password_reset_confirm/<uidb64>/<token>/', auth_view.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
    #      name='password_reset_confirm'),
    # path('password_reset_complete/', auth_view.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
    #      name='password_reset_complete'),
    ]   
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

shop/main/models.py
from django.db import models
from django.forms import ImageField
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser, User
)

# Create your models here.
# class User(models.Model):
#     login = models.CharField("Логин пользователя", max_length=255, blank = True)
    
#     password = models.CharField("Пароль пользователя", max_length=255, blank = True)
    
#     email = models.EmailField("Почта", max_length=255, blank = True)


# class Plots(models.Model):
    
#     title = models.CharField ('Место', blank = True)
    
#     plot= models.TextField('Сюжеты',blank =True)
    
# class Locatins(models.Model):
    
#     location = models.ImageField(upload_to='/')



class MyUserManager(BaseUserManager):
    def create_user(self, email, username, password):
        print('Работай')
        if not email:
            raise ValueError("ENTER AN EMAIL BUDDY")
        if not username:
            raise ValueError("I KNOW YOU HAVE A NAME")
        if not password:
            raise ValueError("PASSWORD?!?!?!? HELLO??")

        Role.objects.get_or_create(name="пользователь")
        role = Role.objects.get(name="пользователь")
        user = self.model(
             email = self.normalize_email(email),
             username = username,
             role = role
             )
        user.set_password(password)
        user.save()
        return user
    def create_superuser(self, username, password, alias=None):
        Role.objects.get_or_create(name="администратор")
        role = Role.objects.get(name="администратор")
        user = self.model(
            username=username,
            role=role
        )
        user.is_admin = True
        user.set_password(password)
        user.save()
        return user
    
    def is_saler(self):
        return self.model.role
    
        



class Role(models.Model):
    name = models.CharField("Наименование роли", max_length=50)

    class Meta:
        verbose_name = "Роль"
        verbose_name_plural = "Роли"
    
    def __str__(self):
        return self.name


class CustomUser(AbstractBaseUser):
    email = models.EmailField(
        verbose_name='Адрес email',
        max_length=255,
        unique=True,
    )

    role = models.ForeignKey(Role, verbose_name="Роль пользователя", on_delete=models.CASCADE)

    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = MyUserManager()
    
    username = models.CharField(
        verbose_name='login',
        max_length=255,
        unique=True,
    )

    USERNAME_FIELD = 'username'
    
    def is_saler(self):
        return self.model.role

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin


class Book (models.Model):
    
    title = models.TextField(name ='title', unique= True)
    first_page = models.ForeignKey('BookPage', null = True,blank=True, on_delete=models.SET_NULL, related_name = 'first_page')
    def __str__(self):
        return '{self.title} ({self.id})'.format(self=self)
    
class BookPage(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE, verbose_name= 'Книга')
    title = models.CharField(max_length = 255 , name ='title', verbose_name= ' Заголовок')
    items = models.ManyToManyField('main.Item', blank=True, verbose_name= 'Предметы')
    body =models.TextField(name='body', verbose_name= 'Основной текст')
    cover_art = models.ImageField(upload_to='book_images', null =True, blank=True, verbose_name= 'Картинка')
    
        
    def __str__(self):
        return '{self.title} ({self.id})'.format(self=self)
    
class PageLink(models.Model):
    from_page = models.ForeignKey(BookPage, on_delete=models.CASCADE)
    to_page = models.ForeignKey(BookPage, related_name ='to_page', on_delete=models.CASCADE,)
    name = models.TextField()
    
    items = models.ManyToManyField('main.Item', blank=True) 
    
    class Meta:
        unique_together = ['from_page', 'to_page']
        
    def __str__(self):
        return '{self.from_page.title} -> {self.to_page.title} ({self.id})'.format(self=self)
     
       
    def has_all_need(self,items):
        return all(i in items for i in self.items.all())
    
class Item (models.Model):
    name = models.TextField()
    
    def __str__(self):
        return '{self.name}'.format(self=self)
        
class BoolProgress (models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    book_page = models.ForeignKey(BookPage, on_delete=models.CASCADE)
    items = models.ManyToManyField(Item, blank=True)
    is_passed = models.BooleanField("Страница пройдена", default=False)

    class Meta:
        unique_together = ['user', 'book']

    @classmethod
    def start_reading(cls, user, book):
        progress = BoolProgress(
            user=user, book=book, book_page=book.first_page,
        )
        progress.save()
        return progress
    
    
# class ProgressSave (models.Model):
   
#     progress  = models.ForeignKey(BoolProgress, on_delete=models.CASCADE)
#     book_page = models.ForeignKey(BookPage, on_delete=models.CASCADE)
#     items = models.ManyToManyField(Item, blank=True) 
    

    
    

shop/main/views.py
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render, get_object_or_404
from . import models, forms
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.views import LoginView, LogoutView

from rest_framework import generics
from rest_framework.permissions import IsAuthenticated, IsAdminUser
from main import serializers, models
from main.models import Book
from django.urls import reverse, reverse_lazy
from .models import BookPage
from django.views.generic import View
from django.views.generic.edit import CreateView
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse
from django.contrib.auth.forms import PasswordResetForm
from main.models import CustomUser
from django.template.loader import render_to_string
from django.db.models.query_utils import Q
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from random import randint


# Create your views here.
def index(request):
    print("gghgfhfghfghgfhgf")
    return render(request, 'main/index.html', context ={
        'books': models.Book.objects.all()
        
    }  )
    
def about(request):
    return render(request, 'main/about.html', context ={
         
    }  )
# def get_random_book():
#     pages_count = BookPage.objects.all().count()
#     rand_page_id = randint(2, pages_count)
    
#     get_current_page = BookPage.objects.filter(id=rand_page_id)
#     ...
#     data = []
    

class RegisterView (CreateView):
    form_class = forms.SignUpForm   
    template_name = 'main/register1.html'
    success_url = reverse_lazy('login')
    success_message = "Your profile was created successfully"
    
    def form_valid(self, form):
        return super(RegisterView, self).form_valid(form)
    
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context['sname'] = 'asdasdasdasd'
        return context
    
def check_admin(user):
    is_saler = False
    print("FFFFFFFFFFFF", user.is_saler())
    if user.is_saler().name == 'Модератор':
        is_saler = True
    
    return is_saler


class UserListView (generics.ListAPIView):
    queryset = models.CustomUser.objects.all()
    serializer_class = serializers.UserSerializer
    permission_classes = [IsAuthenticated]
    
    
class CustomLoginView(LoginView):
    form_class = forms.CustomLoginForm   
    template_name = 'main/login1.html'
    
    def get_success_url(self):
        return reverse_lazy('index')
    
    def form_valid(self, form):
        print ('aaaaaaaaaaaaaaaaa')
        return super().form_valid(form)
    
    
class AddPageView(View):
    def get(self, request: HttpRequest, *args, **kwargs):
        form = forms.BookPageForm
        return render(
            request=request,
            template_name='main/page_add.html',
            context={
                'form' : form
            }
        )
        
    
    def post(self, request, *args ,   **kwargs):
         print(request.POST)
         if request.method == 'POST':
            form = forms.BookPageForm (request.POST)
            print ('ffffffffff', request.POST)
            
            if form.is_valid():
                    print("8888888888888888888888888888888888888888888888888")
                    order = form.save(commit=False)
                    order.save()
                    return redirect('index')
            
                        
            
            return render(request, 'main/page_add.html', context ={'form': form})
        
        
def logout_user(request):
    logout(request)
    messages.success(request, ('Вы вышли'))
    return redirect ('login')


def profile(request):
	return render(request, 'main/index.html')

def password_reset_request(request):
    if request.method == 'POST':
        password_form = PasswordResetForm(request.POST)
        if password_form.is_valid():
            data = password_form.cleaned_data['email']
            user_email = CustomUser.objects.filter(Q(email =data))
            if user_email.exists():
                for user in user_email:
                    subject = 'Сброс пароля'
                    email_template_name = 'main/password_message.txt'
                    parametrs = {
                        'email': user.email,
                        'domain': '127.0.0.1:8000',
                        'site_name': 'One_day',
                        'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                        'token': default_token_generator.make_token(user),
                        'protocol': 'http', 
                    }
                    email = render_to_string(email_template_name, parametrs)
                    try:
                        send_mail(subject, email, '', [user.email], fail_silently=False )
                    except: 
                        return HttpResponse('Invalid Header')
                    return redirect('password_reset_done')
    else:
        password_form = PasswordResetForm()
    context = {
        'password_form': password_form,
    }
    return render (request, 'main/password_reset.html', context)

def on_progress(view):
    def inner(request, book_id, **kwargs):
        try: 
            print ('zzzzzzzzzzzzzzzzzaaaaaaaaaaaaaaaa')
            progress = models.BoolProgress.objects.get(book=book_id, user=request.user)
            print ('sadasdasdasdasdasdasdasdasdasdasdasdas')
        except models.BoolProgress.DoesNotExist:
            return redirect(reverse('book', kwargs={'book_id': book_id}))
        return view (
            request = request, progress = progress, book_id = book_id, **kwargs 
            )
    return inner 

def book(request, book_id):
    b = get_object_or_404(models.Book, id=book_id)
    if not b.first_page:
        print ('_________________________-')
        return render(request, 'main/book.html', context ={'book': b,})
    try: 
        progress = models.BoolProgress.objects.get(book=b, user=request.user)
        print ('zccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc')
    except models.BoolProgress.DoesNotExist:
        progress = models.BoolProgress.start_reading(user = request.user, book = b )
        print ('aaaaaaaaaaaaaaaa')
    return redirect (reverse('page', kwargs={'book_id': b.id, 'page_id': progress.book_page.id,}))

@on_progress
def page(request, progress, book_id, page_id):
    
    page = get_object_or_404(models.BookPage, book__id = book_id, id = page_id,)
    progress.book_page = page
    progress.save()
    
    
    
    links = [(link, link.has_all_need(list(progress.items.all())))
             
             for link in page.pagelink_set.all()
             
             ]
    
    return render (request, 'main/page.html', context={
        'page': page,
        'progress': progress,
        'links': links,
        'page_items': page.items.exclude(id__in = progress.items.only('id')),
        
    })

@on_progress
def take (request,progress, book_id, page_id, item_id ):
   item = get_object_or_404(models.Item, id = item_id)
   progress.items.add(item)
   return redirect (reverse('page', kwargs={'book_id': book_id, 'page_id': page_id,}))

shop/templates/main/about.html
{% extends 'layout.html' %}
{% load static %}

{% block css_add %}
    <link rel="stylesheet" href="{% static 'css/about.css' %}"/>
{% endblock css_add %}


{% block content %}
<div class="about">
    <div class="container">
        <div class="preview-img">
            <img src="/static/css/about1.jpg" alt="preview-img" >
        </div>

        <div class="about_block">
             <p>Этот проект был создан человеком, который хотел сделать хоть что-то с web и сдать курсовую. Хоть он неидеальный и можно было сделать много чего, но оно как-то работает и будет вроде дальше работать. Как разработчик этого сайта хотел бы пожелать вам веселой игры! Сделал этот сайт студент группы ИС-21-3 Нарикбаев Арслан<p>
        </div>
    </div>
</div> 

{% endblock content %}

shop/templates/main/book.html
{% extends 'layout.html' %}
{% load static %}

{% block css_add %}
    <link rel="stylesheet" href="{% static 'css/book.css' %}"/>
{% endblock css_add %}

{% block content %}
<div class="book">
   <div class="container">
      <div class="book_block">
         <h1 >{{book.title}}</h1> 
         <ul>
            {% for page in book.bookpage_set.all %}
            <li><a class="book_title" href ="{% url 'page' book.id page.id %} ">
               {{page.title}}
            </a></li>
            {%endfor%}   
      </ul>
      </div>
   </div>
</div> 
{% endblock %}

shop/templates/main/book1.html
{% extends 'layout.html' %}
{% load static %}
{% comment %} {% block title %}Заголовок{% endblock %} {% endcomment %}
{% block content %}
   <h1>{{book.title}}</h1> 
   <ul>
      {% for page in book.bookpage_set.all %}
      <li><a href ="{% url 'page' book.id page.id %}">
         {{page.title}}
      </a></li>
      {%endfor%}   
   </ul>
{% endblock %}

shop/templates/main/login1.html
{% extends 'layout.html' %}
{% load static %}

{% block css_add %}
    <link rel="stylesheet" href="{% static 'css/login1.css' %}"/>
{% endblock css_add %}


{% block content %}
<div class="login">
    <div class="container">
        <div class="login_block">
             <img 
                    src="/static/css/logo.png" class="img-fluid " width:'200' height:'200'> 
            <h1 class="login_title">Авторизация</h1>

                <form method="POST" action="/login/" >   
                    {% csrf_token %}

                    <div class="form_block">
                        <div class="form_field">Логин<h3>{{ form.username }}</h3></div>
                        <div class="form_field">Пароль<h3>{{ form.password }}</h3></div>
                    </div>

                    <button class="form_btn" type="submit">Авторизация</button>
                </form>
                <button class="form_btn" onclick="window.location.href = '/password_reset/';">Забыли пароль?</button>
                <div class = 'error'>
                    {% if form.errors %}
                        <p class="error-message">Неправильный логин или пароль</p>
                    {% endif %}
                </div>
        </div>
    </div>
</div> 

{% endblock content %}

shop/templates/main/page.html
{% extends 'layout.html' %}
{% load static %}

{% block css_add %}
    <link rel="stylesheet" href="{% static 'css/page.css' %}"/>
{% endblock css_add %}

{% block content %}
<div class="page">
    <div class="container">
        <div class="page_block"> 
            <div class="main_block">
                        <div class="text_block">
                                    {{page.body}}
                                    {% if page_items %}
                                    <h3> Вы видите  </h3>
                                        <ul>
                                            {% for item in page_items %}
                                                <li>
                                                    <a href="{% url 'take' page.book.id page.id item.id %}">
                                                    {{ item.name }}
                                                    </a>
                                                </li>
                                            {% endfor %}
                                        </ul>
                                        {% endif %}
                                    <h3> Куда идти?  </h3>
                                    <ul>      
                                            {% for link, passable in links  %}
                                                <li>
                                                    {% if passable %}
                                                        <a href ="{% url 'page' page.book.id  link.to_page.id %}">
                                                            {{ link.name }}
                                                        </a>
                                                    {% else %}
                                                    {{ link.name }}
                                                    {% endif %}
                                                </li>
                                            {%endfor%}   
                                  </ul>
                        </div>  
                                <div class="item_block">
                                    {% if progress.items.all %}
                                    <h3>Ваш Инвентарь</h3> 
                                    <ul>
                                            {% for item in progress.items.all %}
                                            <li>
                                            {{item.name}}
                                            </a></li>
                                            {%endfor%}   
                                        </ul>
                                    {% endif %}
                                </div>  
                    </div>
                <div class="image_block">
                    <img class ='image_view'src="{{ page.cover_art.url }}" />
                </div>     
        </div>
    </div>
</div> 
{% endblock %}

shop/templates/main/page1.html
{% extends 'layout.html' %}
{% comment %} {% block title %}Заголовок{% endblock %} {% endcomment %}
{% block content %}
   {% comment %} {{page.book.title}}:{{ page.title}} {% endcomment %}
   {{page.body}}
   {% if page_items %}
   <h3> Вы видите  </h3>
    <ul>
        {% for item in page_items %}
              <li>
                <a href="{% url 'take' page.book.id page.id item.id %}">
                  {{ item.name }}
                </a>
              </li>
        {% endfor %}
    </ul>
    {% endif %}
   <h3> Куда идти?  </h3>
   <ul>
        <img src="{{ page.cover_art.url }}" />
        {% for link, passable in links  %}
            <li>
                {% if passable %}
                    <a href ="{% url 'page' page.book.id  link.to_page.id %}">
                        {{ link.name }}
                    </a>
                {% else %}
                {{ link.name }}
                {% endif %}
            </li>
        {%endfor%}   
    </ul>
    {% if progress.items.all %}
    <h3>Ваш Инвентарь</h3> 
    <ul>
            {% for item in progress.items.all %}
            <li>
               {{item.name}}
            </a></li>
            {%endfor%}   
        </ul>
    {% endif %}
{% endblock %}

shop/templates/main/page_add.html
{% extends 'layout.html' %}
{% load static %}
{% load widget_tweaks %}

{% block css_add %}
    <link rel="stylesheet" href="{% static 'css/page_add.css' %}"/>
{% endblock css_add %}

{% block content %}
    {% comment %} <form action="form1.php" method="post"> {% endcomment %}
        {% comment %} <div>Название главы</div> {% endcomment %}
        {% comment %} <input type="text" name="title_page" class = "title_page" required="required"> {% endcomment %}
        <div class = 'container'>
            <div class = 'page_add_block'>
            
                <div class = "text-center">
                    <form method="POST" action = '/page_add'>
                        {% csrf_token %}
                        {% for field in form.visible_fields %}
                            <div class="form-group">
                                {{ field.label_tag }}
                                {% render_field field class="form-control" %}
                            </div>
                        {% endfor %}
                            <input type="submit" id="myButton" class="btn btn-block btn-outline-light" value="Опубликовать">
                    </form>
                </div>
            </div>
        </div>
{% endblock %}

shop/templates/main/password_reset.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}
{% block content %}
{% load static %}
{% block css_add %}
    <link rel="stylesheet" href="{% static 'css/reset_login.css' %}"/>
{% endblock css_add %}

<div class="container">
    <div class="row mt-5 pt-3">
        <div class="col-md-8 offset-md-2">
            <div class="card my-3 shadow">
                <div class="card-body">
                    <h4>Сброс пароля</h4>
                    <hr>
                    <div class="alert alert-info">
                        Напишите сюда ваш email для сброса пароля
                    </div>
                    <form method="POST" >
                        {% csrf_token %}
                        {{ password_form|crispy }}
                        <button class="btn btn-primary btn-block" type="submit">Отправить</button>
                    </form>
                    <hr>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

shop/templates/main/password_reset_complete.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block css_add %}
    <link rel="stylesheet" href="{% static 'css/reset_complete.css' %}"/>
{% endblock css_add %}
{% block content %}
<div class="container">
    <div class="row mt-5 pt-3">
        <div class="col-md-8 offset-md-2">
            <div class="card my-3 shadow">
                <div class="card-body">
                    <h4>Сброс пароля</h4>
                    <hr>
                    <div class="alert alert-info">
                        Вы успешно сбросили пароль. Можете перейти на страницу авторизации
                    </div>
                    <button class="btn btn-primary btn-block" onclick="window.location.href = '/login/';">Логин</button>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

shop/templates/main/password_reset_completed.html
{% extends 'layout.html' %}
{% block title %}Password Reset Complete Page{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
    <div class="row mt-5 pt-3">
        <div class="col-md-8 offset-md-2">
            <div class="card my-3 shadow">
                <div class="card-body">
                    <h4>Password Reset Complete Page</h4>
                    <hr>
                    <div class="alert alert-info">
                        Your password reset is successful. Log in with new credentials
                    </div>
                    <a href="{% url 'users-login' %}">Login</a>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

shop/templates/main/password_reset_confin.html
{% extends 'layout.html' %}
{% block title %}Password Reset Confirm Page{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
    <div class="row mt-5 pt-3">
        <div class="col-md-8 offset-md-2">
            <div class="card my-3 shadow">
                <div class="card-body">
                    <h4>Password Reset Confirm Page</h4>
                    <hr>
                    <form method="POST">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <input class="btn btn-primary btn-block" type="submit" value="Reset Password Confirm">
                    </form>
                    <hr>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

shop/templates/main/password_reset_done.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block css_add %}
    <link rel="stylesheet" href="{% static 'css/reset_done.css' %}"/>
{% endblock css_add %}

{% block content %}
<div class="container">
    <div class="row mt-5 pt-3">
        <div class="col-md-8 offset-md-2">
            <div class="card my-3 shadow">
                <div class="card-body">
                    <h4>Сброс пароля</h4>
                    <hr>
                    <div class="alert alert-info">
                        На ваш email было отправлено письмо с инструкциями
                    </div>
                    <hr>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

shop/templates/main/register.html
{% extends 'layout.html' %}
{% load widget_tweaks %}

{% css_add %}
    <link rel="stylesheet" href="{% static 'css/register.css' %}"/>
{% endblock %}


{% block content %}
{{sname}}
<div class="container-fluid with-image">
    <div class="row">
        {% comment %} <div class="col-12 col-sm-6 col-md-4 col-lg-4 offset-md-4 mt-4"> {% endcomment %}
            <h1 class="text-dark text-center">Регистрация</h1>
            <div class="block p-3 text-center">
                <form method="POST" action="/register" >
                    {% csrf_token %}
                    {% for field in form %}
                        <p><label class ='form-label'a for='{{field.id_for_label}}'>
                            
                            {{ field.label }}: </label>
                            {% render_field field class="form-control" %}
                        </p>
                        <div class = 'form-error'> {{field.errors}}</div>
                    {%endfor%}
                    <input type="submit" id="myButton" class="btn btn-block btn-outline-light" value="Залогиниться">
                </form>
            </div>
        </div>
    </div> 
</div>
{% endblock %}